// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe60sNbPxKaxIiiiI9fQZcErrsrHIJTKE',
    appId: '1:305615956146:web:932945b426d0a55e6d81ab',
    messagingSenderId: '305615956146',
    projectId: 'college-ditto',
    authDomain: 'college-ditto.firebaseapp.com',
    storageBucket: 'college-ditto.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCITe_Jtm7uMU6iL226e29qs87G8WtSC7U',
    appId: '1:305615956146:android:b9575a606710aa806d81ab',
    messagingSenderId: '305615956146',
    projectId: 'college-ditto',
    storageBucket: 'college-ditto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg8O2CysMZhhHxwBGQPYP34WjE2fudUHE',
    appId: '1:305615956146:ios:774e9a3686bb9ff86d81ab',
    messagingSenderId: '305615956146',
    projectId: 'college-ditto',
    storageBucket: 'college-ditto.appspot.com',
    iosClientId: '305615956146-ft46a9e0ovgh6chhqv04k5bbapsj2rrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.ditto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg8O2CysMZhhHxwBGQPYP34WjE2fudUHE',
    appId: '1:305615956146:ios:774e9a3686bb9ff86d81ab',
    messagingSenderId: '305615956146',
    projectId: 'college-ditto',
    storageBucket: 'college-ditto.appspot.com',
    iosClientId: '305615956146-ft46a9e0ovgh6chhqv04k5bbapsj2rrk.apps.googleusercontent.com',
    iosBundleId: 'com.example.ditto',
  );
}
